In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv("D:/jup/loan_data.csv")
data.head()

person_age person_gender person_education  person_income  person_emp_exp  \
0        22.0        female           Master        71948.0               0   
1        21.0        female      High School        12282.0               0   
2        25.0        female      High School        12438.0               3   
3        23.0        female         Bachelor        79753.0               0   
4        24.0          male           Master        66135.0               1   

  person_home_ownership  loan_amnt loan_intent  loan_int_rate  \
0                  RENT    35000.0    PERSONAL          16.02   
1                   OWN     1000.0   EDUCATION          11.14   
2              MORTGAGE     5500.0     MEDICAL          12.87   
3                  RENT    35000.0     MEDICAL          15.23   
4                  RENT    35000.0     MEDICAL          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0                 0.49                         3.0           561   
1                 0.08                         2.0           504   
2                 0.44                         3.0           635   
3                 0.44                         2.0           675   
4                 0.53                         4.0           586   

  previous_loan_defaults_on_file  loan_status  
0                             No            1  
1                            Yes            0  
2                             No            1  
3                             No            1  
4                             No            1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object 
 2   person_education                45000 non-null  object 
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64  
 5   person_home_ownership           45000 non-null  object 
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object 
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64  
 12  previous_loan_defaults_on_file  

In [4]:
X = data.drop(columns=['loan_status'])
y = data['loan_status']

In [5]:
encoders = {col: LabelEncoder() for col in X.columns if X[col].dtype == 'O'}
encoders

{'person_gender': LabelEncoder(),
 'person_education': LabelEncoder(),
 'person_home_ownership': LabelEncoder(),
 'loan_intent': LabelEncoder(),
 'previous_loan_defaults_on_file': LabelEncoder()}

In [6]:
X_encoded = X.copy()
X_encoded

person_age person_gender person_education  person_income  \
0            22.0        female           Master        71948.0   
1            21.0        female      High School        12282.0   
2            25.0        female      High School        12438.0   
3            23.0        female         Bachelor        79753.0   
4            24.0          male           Master        66135.0   
...           ...           ...              ...            ...   
44995        27.0          male        Associate        47971.0   
44996        37.0        female        Associate        65800.0   
44997        33.0          male        Associate        56942.0   
44998        29.0          male         Bachelor        33164.0   
44999        24.0          male      High School        51609.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
0                   0                  RENT    35000.0           PERSONAL   
1                   0                   OWN     1000.0          EDUCATION   
2                   3              MORTGAGE     5500.0            MEDICAL   
3                   0                  RENT    35000.0            MEDICAL   
4                   1                  RENT    35000.0            MEDICAL   
...               ...                   ...        ...                ...   
44995               6                  RENT    15000.0            MEDICAL   
44996              17                  RENT     9000.0    HOMEIMPROVEMENT   
44997               7                  RENT     2771.0  DEBTCONSOLIDATION   
44998               4                  RENT    12000.0          EDUCATION   
44999               1                  RENT     6665.0  DEBTCONSOLIDATION   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score previous_loan_defaults_on_file  
0               561                             No  
1               504                            Yes  
2               635                             No  
3               675                             No  
4               586                             No  
...             ...                            ...  
44995           645                             No  
44996           621                             No  
44997           668                             No  
44998           604                             No  
44999           628                             No  

[45000 rows x 13 columns]

In [7]:
for col in X.columns:
    if X[col].dtype == 'O':
        X_encoded[col] = encoders[col].fit_transform(X[col])
X_encoded

person_age  person_gender  person_education  person_income  \
0            22.0              0                 4        71948.0   
1            21.0              0                 3        12282.0   
2            25.0              0                 3        12438.0   
3            23.0              0                 1        79753.0   
4            24.0              1                 4        66135.0   
...           ...            ...               ...            ...   
44995        27.0              1                 0        47971.0   
44996        37.0              0                 0        65800.0   
44997        33.0              1                 0        56942.0   
44998        29.0              1                 1        33164.0   
44999        24.0              1                 3        51609.0   

       person_emp_exp  person_home_ownership  loan_amnt  loan_intent  \
0                   0                      3    35000.0            4   
1                   0                      2     1000.0            1   
2                   3                      0     5500.0            3   
3                   0                      3    35000.0            3   
4                   1                      3    35000.0            3   
...               ...                    ...        ...          ...   
44995               6                      3    15000.0            3   
44996              17                      3     9000.0            2   
44997               7                      3     2771.0            0   
44998               4                      3    12000.0            1   
44999               1                      3     6665.0            0   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score  previous_loan_defaults_on_file  
0               561                               0  
1               504                               1  
2               635                               0  
3               675                               0  
4               586                               0  
...             ...                             ...  
44995           645                               0  
44996           621                               0  
44997           668                               0  
44998           604                               0  
44999           628                               0  

[45000 rows x 13 columns]

In [35]:
trial_data = pd.concat([X_encoded,y], axis=1)

threshold = 0.03
correlation = trial_data.corr()
high_corr_fect = correlation.index[abs(correlation['loan_status'])>threshold].tolist()
high_corr_fect.remove('loan_status')
print('Selected fectures based on correlation with target:')
print(high_corr_fect)
X_selected = X_encoded[high_corr_fect]

Selected fectures based on correlation with target:
['person_income', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 'loan_percent_income', 'previous_loan_defaults_on_file']


In [9]:
scalar = MinMaxScaler()
X = scalar.fit_transform(X_selected)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X_train

array([[0.01241039, 0.        , 0.42028986, ..., 0.50137174, 0.22727273,
        0.        ],
       [0.00903032, 1.        , 0.33333333, ..., 0.44170096, 0.24242424,
        1.        ],
       [0.04373797, 0.        , 0.68115942, ..., 0.33950617, 0.10606061,
        1.        ],
       ...,
       [0.0069955 , 0.        , 0.29585507, ..., 0.3648834 , 0.27272727,
        1.        ],
       [0.02371855, 1.        , 0.56521739, ..., 0.86213992, 0.16666667,
        0.        ],
       [0.02820806, 0.        , 0.42028986, ..., 0.38340192, 0.10606061,
        1.        ]])

In [12]:
svc = SVC(C=0.5, random_state=42)

In [13]:
svc.fit(X_train, y_train)

SVC(C=0.5, random_state=42)

In [14]:
svc.score(X_test, y_test)

0.9004444444444445

In [15]:
y_pred = svc.predict(X_test)

In [16]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9004444444444445

In [17]:
# test for unknown data

In [18]:
X_new = ['person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file']

In [19]:
"""
['female' 'male']
['Master' 'High School' 'Bachelor' 'Associate' 'Doctorate']
['RENT' 'OWN' 'MORTGAGE' 'OTHER']
['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT' 'DEBTCONSOLIDATION']
['No' 'Yes']
"""

new_data = pd.DataFrame([[12282.0, 'OWN', 1000.0, 'EDUCATION', 11.14, 0.08, 'Yes']], 
                        columns=['person_income', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 
                                 'loan_percent_income', 'previous_loan_defaults_on_file'])
new_data

person_income person_home_ownership  loan_amnt loan_intent  loan_int_rate  \
0        12282.0                   OWN     1000.0   EDUCATION          11.14   

   loan_percent_income previous_loan_defaults_on_file  
0                 0.08                            Yes

In [20]:
new_data_encoded = new_data.copy()

In [21]:
for col in X_new:
    new_data_encoded[col] = encoders[col].transform(new_data[col])
new_data_encoded

person_income  person_home_ownership  loan_amnt  loan_intent  \
0        12282.0                      2     1000.0            1   

   loan_int_rate  loan_percent_income  previous_loan_defaults_on_file  
0          11.14                 0.08                               1

In [22]:
new_data_enc_scaled = scalar.transform(new_data_encoded)

In [23]:
new_pred = svc.predict(new_data_enc_scaled)
new_pred

array([0], dtype=int64)

In [24]:
if new_pred == 1:
    print("🟢 Congrulations!!.., your loan has been approved")
else:
    print("🔴 Sorry to say, your loan has not been approved")

🔴 Sorry to say, your loan has not been approved


In [25]:
data.loc[1,['person_income', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 
    'loan_percent_income', 'previous_loan_defaults_on_file', 'loan_status']].values

array([12282.0, 'OWN', 1000.0, 'EDUCATION', 11.14, 0.08, 'Yes', 0],
      dtype=object)